services:
  - type: web
    name: outlier-management
    runtime: python
    buildCommand: "pip install -r requirements.txt && python -c \"from app import app, db; app.app_context().push(); db.create_all()\""
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: true
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1